---
## Various settings regarding the installation
release_version: '{{ dir_name }}'
prod_dir: "{{prod_clone_root_dir}}/{{release_version}}"
dev_dir: "{{dev_clone_root_dir}}/{{release_version}}"
install_dest: "{{ prod_dir if (env == 'prod') else dev_dir}}"
git_feature_branch: '{{ version }}'
git_checkout_branch: "{{ 'tags' if (git_tagged_version == 'true') else 'origin' }}"
git_tagged_version: '{{ tagged_version }}'
git_refspec_local: "{{ 'refs/tags' if (git_tagged_version == 'true') else 'refs/heads' }}"
git_refspec_remote: "{{ 'refs/remotes/tags' if (git_tagged_version == 'true') else 'refs/remotes/origin' }}"
git_access_token: "6076520f6c6e0046d1468f471e717d2d32738f68"
git_host: "github.com"
git_username: "EBI-Metagenomics"
git_repo_name: "fetch_tool"