repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
# Disabled, there are too many too tackle ATM
# - repo: https://gitlab.com/pycqa/flake8
#   rev: 3.9.2
#   hooks:
#   - id: flake8
#     language: python
