language: python
python:
  - "3.5"
  - "3.6"
env:
  - TEST_SUITE=integration
  - TEST_SUITE=unit

services:
  - docker

install:
  - python setup.py install
  - pip install -r requirements-test.txt

script:
  - pytest -s -vv tests/$TEST_SUITE/

# Only build and deploy docker container once per push
deploy:
  provider: script
  script: bash ./docker_trigger_build.sh
  on:
    branch: master
    python: 3.6
    condition: "$TEST_SUITE = unit"
