#Download base image ubuntu 20.04
FROM ubuntu:20.04
# LABEL about the custom image
LABEL maintainer="sninidakis@hcmr.gr,hariz-zaf@hcmr.gr"
LABEL version="0.1"
LABEL description="EBI Fetch Tool Docker Image."
# Update Ubuntu Software repository
RUN apt update
RUN apt-get install git -y
RUN apt install python3.8 -y && apt install python3-pip -y
RUN mkdir /app
WORKDIR /app
RUN git clone https://github.com/EBI-Metagenomics/fetch_tool.git
WORKDIR /app/fetch_tool
RUN pip3 install -r requirements.txt 
RUN pip3 install pre-commit && pre-commit install
WORKDIR /app/
RUN pip3 install -U fetch_tool/
RUN pwd
WORKDIR /app/fetch_tool
# Aspera is an IBM library for data sharing
RUN chmod +x install-aspera.sh
RUN apt-get install curl -y
RUN ./install-aspera.sh
RUN export PATH=$PATH:/app/fetch_tool/aspera-cli/cli/bin
WORKDIR /app/
CMD [ fetch-read-tool ]
